enableGlobalCache: true

checksumBehavior: update

nmHoistingLimits: dependencies

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
