/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155BurnableUpgradeable } from "./ERC1155BurnableUpgradeable";
export type { ERC1155SupplyUpgradeable } from "./ERC1155SupplyUpgradeable";
export type { IERC1155MetadataURIUpgradeable } from "./IERC1155MetadataURIUpgradeable";
