/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AccessControlUpgradeable__factory } from "./AccessControlUpgradeable__factory";
export { IAccessControlUpgradeable__factory } from "./IAccessControlUpgradeable__factory";
