sequenceDiagram
autonumber

    Note over AssetOwner, AssetUpgrader: Upgrade Asset

    AssetOwner->>+AssetUpgrader:upgrade(id,catalyst,gems)
    opt if(not nft)
        AssetUpgrader->>+Asset:extractERC721(id)
        Asset->>-AssetUpgrader:id
    end
    AssetUpgrader->>GemsAndCatalysts:burn(catalyst,gems)
    AssetUpgrader->>SAND:transferFrom(artist,feeRecipient,fee*supply)
    AssetUpgrader->>-CatalystRegistry:record(id,catalyst,gems)
