site_name: The Sandbox Game
site_url: https://the-sandbox-game.readthedocs.io
theme:
  name: material
  features:
    - navigation.indexes
nav:
  - Getting started:
      - Install: intro/index.md
      - Running the tests: intro/running-tests.md
      - Setting environment variables: intro/setting-environment-variables.md
  - How to:
      - Fixing tests: howto/fixing-tests.md
      - Deploying contracts:
          - General: howto/deploying-contracts.md
          - Deploying asset: howto/deploying-asset.md
      - Preparing a LAND sale: howto/preparing-land-sale.md
      - Preparing an ASSET giveaway: howto/preparing-asset-giveaway.md
      - Generating liquidity pool rewards: howto/generating-liquidity-pool-rewards.md
      - Running a lottery: howto/running-lottery.md
      - Use Faucet to get Sand: howto/use-faucet-to-get-sand.md
      - Deploy subgraph: howto/deploy-subgraph/deploying-subgraph.md
      - Preparing a multi giveaway: howto/preparing-multi-giveaway.md
  - Tutorials:
      - Developing your first feature: tutorials/developing-first-feature.md
      - Writing documentation: tutorials/writing-documentation.md
      - Writing tests: tutorials/writing-tests.md
  - Topics:
      - Blockchain:
          - Ethereum: topics/blockchain/ethereum.md
          - Features: topics/blockchain/features.md
          - Deployment diagram: topics/blockchain/deployment-diagram.md
      - Polygon:
          - Polygon at Sandbox: topics/polygon/polygon.md
      - Asset:
          - Asset: topics/asset/asset.md
          - Asset attributes registry: topics/asset/asset-attributes-registry.md
          - Asset minter: topics/asset/asset-minter.md
          - Asset upgrader: topics/asset/asset-upgrader.md
          - Asset signed auction: topics/asset/asset-signed-auction.md
          - Giveaway:
              - Single: topics/asset/giveaway/single.md
              - Multiple: topics/asset/giveaway/multiple.md
      - Solidity:
          - Guideline: topics/guideline/solidity.md
      - DeFi:
          - Liquidity provider:
              - SAND staking: topics/defi/liquidity-provider/sand-staking.md
          - Sand Reward Pool: topics/defi/sand-reward-pool.md
          - ERC20 Reward Pool: topics/defi/erc20-reward-pool.md
      - Catalyst:
          - Gems & catalysts: topics/catalyst/catalyst.md
          - Old gems & catalysts migration: topics/catalyst/migration-catalyst.md
      - Sand:
          - Sand Token: topics/sand/sand-token.md
          - Bundle Sand Sale: topics/sand/bundle-sand-sale.md
          - ERC20 giveaway: topics/claims/signed-erc20-giveaway.md
      - Token:
          - EIP712: topics/token/EIP712.md
          - ERC20: topics/token/ERC20.md
          - ERC1155721: topics/token/ERC1155721.md
      - Land:
          - Land: topics/land/land.md
      - Game:
          - Game: topics/game/game.md
      - Permit:
          - Permit: topics/permit/Permit.md
      - Faucet:
          - Faucet: topics/faucet/Faucet.md
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: '#'
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
