/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC1155BurnableUpgradeable__factory } from "./ERC1155BurnableUpgradeable__factory";
export { ERC1155SupplyUpgradeable__factory } from "./ERC1155SupplyUpgradeable__factory";
export { IERC1155MetadataURIUpgradeable__factory } from "./IERC1155MetadataURIUpgradeable__factory";
