/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessControlUpgradeable } from "./AccessControlUpgradeable";
export type { IAccessControlUpgradeable } from "./IAccessControlUpgradeable";
